services:
  web:
    build: .
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
    depends_on:
      db:
        condition: service_healthy
  worker:
    build: .
    command: sh -c "sleep 10 && python -m app.worker"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+psycopg://app:app@db:5432/app
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
      web:
        condition: service_started
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 20
volumes:
  pgdata:
