name: CD

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

  # Optional: Koyeb deploy via API (set secrets KOYEB_API_TOKEN, KOYEB_APP_ID)
  # deploy-koyeb:
  #   needs: publish-image
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy on Koyeb
  #       run: |
  #         echo "Trigger deployment via Koyeb API with new image tag"
  #         # Placeholder: call Koyeb CLI/API to update the service to ghcr.io/${{ github.repository }}:${{ github.ref_name }}